name: build-and-push-gemma-image 

on:
  workflow_dispatch:  # Manual trigger for now

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Login to Docker Hub 
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get lowercase repo name
        id: repo_name 
        run: |
          lowercase_name=$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')
          echo "::set-output name=repo_name::${lowercase_name}"

      - name: Build and push GEMMA image
        id: docker_build_gemma
        uses: docker/build-push-action@v4.0.0
        with:
          context: .  # Use the repository root as context
          file: LUQGemmaDockerfile  # Your Dockerfile's name
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            miguelcleon412/${{ steps.repo_name.outputs.repo_name }}:latest 
                # Replace 'your-dockerhub-username' 

      - name: Image digest
        run: echo ${{ steps.docker_build_gemma.outputs.digest }} 
